install:
	poetry install

brain-games:
	poetry run brain_games

build:
	poetry build

publish:
	poetry publish --dry-run

package-install:
	python3 -m pip install --user dist/*.whl
brain-even:
	python3 brain_even.py.save
brain-calc:
	python3 brain_calc.py
brain-gcd:
	python3 brain_gcd.py
brain-progression:
	python3 brain_progression.py
brain-prime:
	python3 brain_prime.py
