install:
	poetry install

brain-games:
	poetry run brain_games

build:
	poetry build

publish:
	poetry publish --dry-run

package-install:
	python3 -m pip install --user dist/*.whl
brain-even:
	python3 brain_even.py.save
brain-calc:
	python3 brain_calc.py
