[tool.poetry]
name = "hexlet-code"
version = "0.1.0"
description = "Brain games - training project number one"
authors = ["Milena Egiaze <milena.egiazaryan77@mail.ru>"]
repository = "https://github.com/megiazavr/python-project-49/tree/main"
description = ""
classifiers = [ "Topic :: Software Development :: Programming basics"]
authors = ["Milena Egiaze"]
repository = "https://github.com/megiazavr/python-project-49"
readme = "README.md"
packages = [
  {include = "brain_games"},
]
classifiers = [
    "Topic :: Education"
]

[tool.poetry.dependencies]
python = "^3.11"
prompt = "^0.4.1"

[tool.poetry.group.dev.dependencies]
flake8 = "^7.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
<<<<<<< HEAD
brain-games = "brain_games.scripts.games:main"
brain-even = "brain_games.scripts.even:main"
brain-calc = "brain_games.scripts.calc:main"
brain-gcd = "brain_games.scripts.gcd:main"
brain-progression = "brain_games.scripts.progression:main"
brain-prime = "brain_games.scripts.prime:main"
=======
brain-games = "brain_games.scripts.brain_games:main"
brain-even = "brain_games.scripts.brain_even:main"
brain-calc = "brain_games.scripts.brain_calc:main"
brain-gcd = "brain_games.scripts.brain_gcd:main"
brain-progression = "brain_games.scripts.brain_progression:main"
brain-prime = "brain_games.scripts.brain_prime:main"
 
>>>>>>> 288bfbb (update pyproject.toml)
